import { useState, useMemo } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import {
  BookOpen,
  CheckCircle2,
  Plus,
  RefreshCw,
  Search,
  Trash2,
  Layers,
  History,
  XCircle,
  FileText,
  Download,
  Edit3,
  Archive,
} from 'lucide-react';
import { PageWrapper } from '@/components/layout/PageWrapper';
import { Card } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { PageSpinner, Spinner } from '@/components/ui/Spinner';
import { CreateContentModal } from '@/components/shared/CreateContentModal';
import { Modal, Sheet } from '@/components/ui';
import { runbookApi } from '@/services/api/endpoints';
import { formatDuration, formatRelativeTime } from '@/utils/formatters';
import { cn } from '@/utils/cn';
import { Table, THead, TBody, TR, TH, TD } from '@/components/ui/Table';
import type { Runbook } from '@/types';

import { useToast } from '@/hooks/useToast';

import { storage } from '@/services/storage';
import { appConfig } from '@/config/app.config';

type FilterTab = 'ALL' | 'ACTIVE' | 'PROCESSING' | 'FAILED' | 'ARCHIVED';
type DetailTab = 'steps' | 'history';

export default function Runbooks() {
  const [search, setSearch] = useState('');
  const [filterTab, setFilterTab] = useState<FilterTab>('ALL');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [modalType, setModalType] = useState<'Runbook' | 'Article'>('Runbook');
  const [selectedRunbook, setSelectedRunbook] = useState<Runbook | null>(null);
  const [activeDetailTab, setActiveDetailTab] = useState<DetailTab>('steps');

  const queryClient = useQueryClient();
  const { success, error } = useToast();

  const { data, isLoading } = useQuery<Runbook[]>({
    queryKey: ['runbooks'],
    queryFn: () => runbookApi.list(),
  });

  const uploadMutation = useMutation({
    mutationFn: (files: File[]) => runbookApi.upload(files),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['runbooks'] });
      setIsModalOpen(false);
      success('Upload Successful', 'Your runbook is being processed.');
    },
  });

  const handleCreate = async (data: { files: File[] }) => {
    if (data.files.length > 0) {
      uploadMutation.mutate(data.files);
    }
  };

  const [archivedIds, setArchivedIds] = useState<Set<string | number>>(() => {
    const saved = localStorage.getItem('archived_runbooks');
    return new Set(saved ? JSON.parse(saved) : []);
  });

  const handleArchive = (id: string | number) => {
    const next = new Set(archivedIds);
    next.add(id);
    setArchivedIds(next);
    localStorage.setItem('archived_runbooks', JSON.stringify(Array.from(next)));
    setSelectedRunbook(null);
    success('Runbook Archived', 'The runbook has been archived locally.');
  };

  const handleDownload = (rb: Runbook) => {
    // Generate a text guide directly from the runbook data on the frontend
    const name = typeof rb.name === 'string' ? rb.name : (rb.summary?.name || 'Unnamed Runbook');
    const description = renderDescription(rb);
    const steps = rb.steps || rb.execution_steps || [];
    
    let content = `RUNBOOK GUIDE: ${name.toUpperCase()}\n`;
    content += `==========================================\n\n`;
    content += `DESCRIPTION:\n${description}\n\n`;
    content += `STEPS:\n`;
    
    if (steps.length > 0) {
      steps.forEach((step) => {
        content += `${step.order}. ${step.title}\n`;
        if (step.command) content += `   Command: ${step.command}\n`;
        content += `\n`;
      });
    } else {
      content += `No automated steps defined for this runbook.\n`;
    }
    
    content += `\n------------------------------------------\n`;
    content += `Generated by AgenticOps - ${new Date().toLocaleString()}\n`;

    // Create a blob and trigger download from the frontend only
    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_guide.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
    
    success('Guide Generated', 'Text guide has been downloaded from the browser.');
  };

  const filtered = useMemo(() => {
    let list = data ?? [];
    if (search) {
      const s = search.toLowerCase();
      list = list.filter((rb) => {
        const nameRaw = typeof rb.name === 'object' ? (rb.summary?.name || '') : (rb.name || '');
        const name = typeof nameRaw === 'string' ? nameRaw : '';
        
        const summaryNameRaw = rb.summary?.name || '';
        const summaryName = typeof summaryNameRaw === 'string' ? summaryNameRaw : '';
        
        const categoryRaw = rb.summary?.category || (typeof rb.category === 'string' ? rb.category : '');
        const category = typeof categoryRaw === 'string' ? categoryRaw : '';
        
        const descRaw = typeof rb.description === 'object' ? (rb.summary?.description || '') : (rb.description || '');
        const desc = typeof descRaw === 'string' ? descRaw : '';
        
        const summaryDescRaw = rb.summary?.description || rb.summary?.summary || '';
        const summaryDesc = typeof summaryDescRaw === 'string' ? summaryDescRaw : '';

        return (
          name.toLowerCase().includes(s) ||
          summaryName.toLowerCase().includes(s) ||
          category.toLowerCase().includes(s) ||
          desc.toLowerCase().includes(s) ||
          summaryDesc.toLowerCase().includes(s)
        );
      });
    }

    if (filterTab === 'ALL') {
      // Show everything except archived in the main view
      list = list.filter((rb) => !archivedIds.has(rb.id) && rb.status !== 'archived');
    } else if (filterTab === 'ARCHIVED') {
      list = list.filter((rb) => archivedIds.has(rb.id) || rb.status === 'archived');
    } else {
      const statusMap: Record<FilterTab, string> = {
        ALL: '',
        ACTIVE: 'active',
        PROCESSING: 'processing',
        FAILED: 'failed',
        ARCHIVED: 'archived',
      };
      list = list.filter((rb) => rb.status === statusMap[filterTab] && !archivedIds.has(rb.id));
    }

    return list;
  }, [data, search, filterTab, archivedIds]);

  const stats = [
    {
      label: 'TOTAL RUNBOOKS',
      value: data?.length || 0,
      sub: 'tracked operational SOPs',
      icon: BookOpen,
      color: 'text-indigo-500',
    },
    {
      label: 'ACTIVE',
      value: data?.filter((r) => r.isActive).length || 0,
      sub: 'indexed in vector DB',
      icon: CheckCircle2,
      color: 'text-emerald-500',
    },
    {
      label: 'PROCESSING',
      value: 0,
      sub: 'being chunked & embedded',
      icon: RefreshCw,
      color: 'text-amber-500',
    },
    {
      label: 'INDEXED CHUNKS',
      value: (data?.length || 0) * 35,
      sub: 'vectors in Chroma',
      icon: Layers,
      color: 'text-cyan-500',
    },
  ];

  const renderDescription = (rb: Runbook) => {
    const desc = rb.summary?.description || rb.summary?.summary || rb.description;
    if (typeof desc === 'object' && desc !== null) {
      return (desc as any).description || (desc as any).summary || (desc as any).overview || 'No description available.';
    }
    return desc || 'No description available.';
  };

  if (isLoading) return <PageSpinner />;

  return (
    <PageWrapper bare>
      <div className="mx-auto w-full max-w-7xl px-4 sm:px-6 py-8 space-y-8">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <h1 className="text-2xl font-bold flex items-center gap-2.5 text-slate-900">
              <BookOpen className="h-7 w-7 text-slate-800" /> Runbooks
            </h1>
            <p className="text-slate-500 text-sm mt-1">
              Upload PDF/DOCX runbooks · stored locally · indexed into the RAG vector store
            </p>
          </div>
          <div className="flex items-center gap-3">
            <Button
              variant="outline"
              size="sm"
              className="bg-white border-slate-200 text-slate-600 font-bold text-[11px] tracking-widest h-10 px-4"
              leftIcon={<RefreshCw className="h-3.5 w-3.5" />}
              onClick={() => queryClient.invalidateQueries({ queryKey: ['runbooks'] })}
            >
              REFRESH
            </Button>
            <Button
              size="sm"
              className="bg-slate-900 text-white hover:bg-slate-800 font-bold text-[11px] tracking-widest h-10 px-5"
              leftIcon={<Plus className="h-4 w-4" />}
              onClick={() => {
                setModalType('Runbook');
                setIsModalOpen(true);
              }}
            >
              UPLOAD RUNBOOK
            </Button>
          </div>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
          {stats.map((s) => (
            <Card key={s.label} className="p-6 border-slate-100 shadow-sm hover:shadow-md transition-shadow">
              <div className="flex justify-between items-start">
                <p className="text-[10px] font-bold text-slate-400 tracking-widest uppercase">
                  {s.label}
                </p>
                <div
                  className={cn(
                    'p-2 rounded-xl bg-white border border-slate-100 shadow-sm',
                    s.color,
                  )}
                >
                  <s.icon className="h-5 w-5" />
                </div>
              </div>
              <div className="mt-5">
                <h3 className="text-4xl font-bold text-slate-900">{s.value}</h3>
                <p className="text-[11px] text-slate-400 mt-2 font-medium italic">
                  {s.sub}
                </p>
              </div>
            </Card>
          ))}
        </div>

        {/* Filter/Search Bar */}
        <Card className="p-2 border-slate-100 shadow-sm">
          <div className="flex flex-col sm:flex-row items-center gap-4">
            <div className="relative flex-1 w-full">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
              <Input
                placeholder="Search runbooks, tags, or descriptions..."
                className="pl-11 border-none shadow-none focus-visible:ring-0 bg-transparent text-sm h-11"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>
            <div className="flex items-center gap-1.5 pr-2 w-full sm:w-auto overflow-x-auto pb-2 sm:pb-0 scrollbar-hide">
              {(['ALL', 'ACTIVE', 'PROCESSING', 'FAILED', 'ARCHIVED'] as FilterTab[]).map(
                (tab) => (
                  <button
                    key={tab}
                    onClick={() => setFilterTab(tab)}
                    className={cn(
                      'px-4 py-1.5 text-[10px] font-bold rounded-lg transition-all whitespace-nowrap tracking-widest',
                      filterTab === tab
                        ? 'bg-slate-900 text-white shadow-lg shadow-slate-200'
                        : 'text-slate-400 hover:text-slate-600 hover:bg-slate-50',
                    )}
                  >
                    {tab}
                  </button>
                ),
              )}
            </div>
          </div>
        </Card>

        {/* Table View */}
        <Card className="overflow-hidden border-slate-100 shadow-sm rounded-xl">
          <Table className="border-none">
            <THead className="bg-slate-50/50 border-b border-slate-100">
              <TR className="hover:bg-transparent border-none">
                <TH className="px-8 py-5 text-slate-400 text-[10px] tracking-widest font-bold">RUNBOOK</TH>
                <TH className="px-6 py-5 text-slate-400 text-[10px] tracking-widest font-bold">CATEGORY</TH>
                <TH className="px-6 py-5 text-slate-400 text-[10px] tracking-widest font-bold">SOURCE</TH>
                <TH className="px-6 py-5 text-slate-400 text-[10px] tracking-widest font-bold text-center">CHUNKS</TH>
                <TH className="px-6 py-5 text-slate-400 text-[10px] tracking-widest font-bold text-center">STATUS</TH>
                <TH className="px-6 py-5 text-slate-400 text-[10px] tracking-widest font-bold">UPDATED</TH>
                <TH className="px-8 py-5 text-slate-400 text-[10px] tracking-widest font-bold text-right">ACTIONS</TH>
              </TR>
            </THead>
            <TBody>
              {filtered.map((rb) => (
                <TR key={rb.id} className="group hover:bg-slate-50/50 transition-colors border-slate-50">
                  <TD className="px-8 py-6">
                    <div className="flex items-center gap-3">
                      <span className="font-bold text-[15px] text-slate-800">
                        {typeof rb.name === 'object' ? 'Unnamed Runbook' : (rb.summary?.name || rb.name || 'Unnamed Runbook')}
                      </span>
                      <Badge
                        variant="outline"
                        className="bg-blue-50/50 text-blue-600 border-blue-100/50 text-[9px] font-bold px-1.5 h-5 flex items-center justify-center tracking-tighter"
                      >
                        RAG
                      </Badge>
                    </div>
                    <p className="text-xs text-slate-400 mt-1.5 line-clamp-1 max-w-md font-medium">
                      {renderDescription(rb)}
                    </p>
                  </TD>
                  <TD className="px-6 py-6">
                    <span className="text-[11px] font-bold text-slate-700 tracking-wider uppercase">
                      {rb.summary?.category || rb.category || 'GENERAL'}
                    </span>
                  </TD>
                  <TD className="px-6 py-6">
                    <Badge
                      variant="outline"
                      className="text-[10px] font-bold text-slate-500 border-slate-200 bg-white"
                    >
                      PDF
                    </Badge>
                  </TD>
                  <TD className="px-6 py-6 text-center">
                    <span className="text-sm font-bold text-slate-700">35</span>
                  </TD>
                  <TD className="px-6 py-6 text-center">
                    <Badge
                      variant={
                        rb.status === 'active' ? 'success' : 
                        rb.status === 'processing' ? 'info' : 
                        rb.status === 'failed' ? 'critical' : 
                        'muted'
                      }
                      className="text-[10px] font-bold uppercase tracking-widest px-2.5 h-6"
                    >
                      {rb.status || 'INACTIVE'}
                    </Badge>
                  </TD>
                  <TD className="px-6 py-6 whitespace-nowrap">
                    <span className="text-[13px] text-slate-400 font-medium">
                      {formatRelativeTime(rb.updatedAt || rb.lastUpdated || rb.createdAt || new Date())}
                    </span>
                  </TD>
                  <TD className="px-8 py-6">
                    <div className="flex items-center justify-end gap-5">
                      <button 
                        onClick={() => {
                          setSelectedRunbook(rb);
                          setActiveDetailTab('steps');
                        }}
                        className="text-[11px] font-bold text-slate-400 hover:text-indigo-600 transition-colors tracking-widest"
                      >
                        VIEW
                      </button>
                      <button className="text-slate-300 hover:text-rose-500 transition-all transform hover:scale-110">
                        <Trash2 className="h-4 w-4" />
                      </button>
                    </div>
                  </TD>
                </TR>
              ))}
            </TBody>
          </Table>
        </Card>
      </div>

      {/* Runbook Detail Sidebar */}
      <Sheet
        open={!!selectedRunbook}
        onClose={() => setSelectedRunbook(null)}
        size="md"
        title={
          selectedRunbook && (
            <div className="flex items-start gap-4">
              <div className="p-3 bg-slate-900 rounded-xl shadow-lg shadow-slate-200">
                <FileText className="h-6 w-6 text-white" />
              </div>
              <div className="flex flex-col gap-2">
                <div className="flex items-center gap-2">
                  <Badge variant="outline" className="bg-white border-slate-200 text-slate-700 text-[9px] font-bold tracking-widest px-2 h-5">
                    {selectedRunbook.summary?.category || selectedRunbook.category || 'GENERAL'}
                  </Badge>
                  <Badge variant="outline" className="bg-amber-50 border-amber-100 text-amber-600 text-[9px] font-bold tracking-widest px-2 h-5">
                    MEDIUM RISK
                  </Badge>
                </div>
                <h2 className="text-xl font-bold text-slate-900 leading-tight">
                  {typeof selectedRunbook.name === 'object' ? 'Unnamed Runbook' : (selectedRunbook.summary?.name || selectedRunbook.name || 'Unnamed Runbook')}
                </h2>
                <p className="text-[11px] text-slate-400 font-medium">
                  Updated by <span className="text-slate-500 font-bold">system_agent</span> · {formatRelativeTime(selectedRunbook.updatedAt || selectedRunbook.lastUpdated || selectedRunbook.createdAt || new Date())}
                </p>
              </div>
            </div>
          )
        }
        footer={
          selectedRunbook && (
            <div className="flex items-center justify-between w-full">
              <div className="flex items-center gap-2">
               
                <Button 
                  variant="outline" 
                  size="sm" 
                  className="h-9 px-3 text-[10px] font-bold border-slate-200 text-slate-600 tracking-widest" 
                  leftIcon={<Archive className="h-3.5 w-3.5" />}
                  onClick={() => handleArchive(selectedRunbook.id)}
                  disabled={archivedIds.has(selectedRunbook.id) || selectedRunbook.status === 'archived'}
                >
                  {archivedIds.has(selectedRunbook.id) || selectedRunbook.status === 'archived' ? 'ARCHIVED' : 'ARCHIVE'}
                </Button>
              </div>
              <Button 
                size="sm" 
                className="h-10 px-5 text-[10px] font-bold bg-slate-900 text-white tracking-widest" 
                leftIcon={<Download className="h-4 w-4" />}
                onClick={() => handleDownload(selectedRunbook)}
              >
                DOWNLOAD GUIDE
              </Button>
            </div>
          )
        }
      >
        {selectedRunbook && (
          <div className="space-y-8">
            <div className="space-y-4">
              <h4 className="text-[10px] font-bold text-slate-400 tracking-widest uppercase">Description</h4>
              <p className="text-[13px] text-slate-600 leading-relaxed font-medium">
                {renderDescription(selectedRunbook)}
              </p>
            </div>

            <div className="space-y-6">
              <div className="flex border-b border-slate-100">
                {[
                  { id: 'steps', label: 'Steps', icon: BookOpen },
                ].map((tab) => (
                  <button
                    key={tab.id}
                    onClick={() => setActiveDetailTab(tab.id as DetailTab)}
                    className={cn(
                      'flex items-center gap-2 px-4 py-3 text-[11px] font-bold transition-all border-b-2 tracking-widest uppercase',
                      activeDetailTab === tab.id
                        ? 'border-slate-900 text-slate-900'
                        : 'border-transparent text-slate-400 hover:text-slate-600'
                    )}
                  >
                    <tab.icon className="h-3.5 w-3.5" />
                    {tab.label}
                  </button>
                ))}
              </div>

              <div className="py-2">
                <StepsTab runbook={selectedRunbook} />
              </div>
            </div>
          </div>
        )}
      </Sheet>

      <CreateContentModal
        isOpen={isModalOpen}
        type={modalType}
        onClose={() => setIsModalOpen(false)}
        onSubmit={handleCreate}
        isLoading={uploadMutation.isPending}
      />
    </PageWrapper>
  );
}

// --- Subcomponents ---

function StepsTab({ runbook }: { runbook: Runbook }) {
  const steps = runbook.steps || runbook.execution_steps || [];
  if (steps.length === 0) return <p className="text-sm text-muted-foreground py-4">No steps defined.</p>;
  
  return (
    <ol className="space-y-3">
      {steps.map((step) => (
        <li key={step.order} className="flex gap-4 p-3 rounded-lg border border-slate-100 bg-slate-50/50">
          <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-slate-900 text-white text-[10px] font-bold">
            {step.order}
          </span>
          <div className="flex-1">
            <p className="text-sm font-bold text-slate-800">{step.title}</p>
            {step.command && (
              <pre className="mt-2 p-3 rounded bg-slate-900 text-slate-50 text-[11px] font-mono overflow-x-auto">
                {step.command}
              </pre>
            )}
          </div>
        </li>
      ))}
    </ol>
  );
}

function HistoryTab({ runbookId }: { runbookId: string | number }) {
  const { data, isLoading } = useQuery({
    queryKey: ['runbook-executions', runbookId],
    queryFn: () => runbookApi.executions(runbookId, 20),
  });

  if (isLoading) return <Spinner size="md" className="py-8" />;
  if (!data || data.length === 0) return <p className="text-sm text-muted-foreground py-4 text-center">No execution history found.</p>;

  return (
    <div className="space-y-3">
      {data.map((ex) => (
        <div key={ex.executed_at} className="p-4 rounded-lg border border-slate-100 flex items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            {ex.success ? <CheckCircle2 className="h-5 w-5 text-emerald-500" /> : <XCircle className="h-5 w-5 text-rose-500" />}
            <div>
              <p className="text-sm font-bold text-slate-800 line-clamp-1">{ex.subject}</p>
              <p className="text-[10px] text-slate-400 mt-0.5">{formatRelativeTime(ex.executed_at)} · {formatDuration(ex.duration_s || 0)}</p>
            </div>
          </div>
          <Badge variant="outline" className="text-[10px] font-bold">{ex.status}</Badge>
        </div>
      ))}
    </div>
  );
}
